name: Download Cloudreve To Release

on:
 # push:
   # branches: 
    #  - main
 # schedule: 
   # - cron: 0 12 * * *
  workflow_dispatch: 
  watch:
    types: started

jobs: 
  build: 
    runs-on: ubuntu-latest
    steps: 
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Download cloudreve
        uses: houqp/download-release-assets-action@v1.0.1
        with:
          repo: cloudreve/Cloudreve
          match: "cloudreve_.+_linux_amd64.tar.gz$"
          rename: cloudreve_linux_amd64.tar.gz

      - name: Download cloudreve SharePoint
        uses: houqp/download-release-assets-action@v1.0.1
        with:
          repo: moeYuiYui/Cloudreve
          match: "cloudreve_sp_.+_linux_amd64.tar.gz$"
          rename: cloudreve_sp_linux_amd64.tar.gz

     # - name: Create Release
       # uses: tix-factory/release-manager@v1
       # with:
         # github_token: ${{ secrets.github_token }}
         # mode: uploadReleaseAsset
         # filePath: ./cloudreve_linux_amd64.tar.gz
         # assetName: cloudreve_linux_amd64.tar.gz
         # tag: Cloudreve

     # - name: Create Release SharePoint
       # uses: tix-factory/release-manager@v1
       # with:
         # github_token: ${{ secrets.github_token }}
         # mode: uploadReleaseAsset
         # filePath: ./cloudreve_sp_linux_amd64.tar.gz
         # assetName: cloudreve_sp_linux_amd64.tar.gz
         # tag: Cloudreve

      - name: Delete Release Cloudreve
        uses: Xotl/cool-github-releases@v1.1.2
        with:
          mode: delete
          tag_name: Cloudreve
          github_token: ${{ github.token }}

      - name: Create Release Cloudreve
        uses: Xotl/cool-github-releases@v1.1.2
        with:
          mode: update
          tag_name: Cloudreve
          release_name: "Cloudreve"
          assets: cloudreve_linux_amd64.tar.gz;cloudreve_sp_linux_amd64.tar.gz;
          github_token: ${{ github.token }}
